#!/usr/bin/env python3
"""
ATTEMPT E3 -- Landauer erasure entropy for collapsing the Obata conformal orbit
to ONE member, vs the flash entropy budget S_rad = (4/3) S_BH.

Question 1: erasure cost of the orbit collapse; is it <= the flash budget (affordable)?
Question 2: is there a MINIMUM-cost member (=> a selection), or is the cost the
            same for every member (=> only a cost, no selector)?

Owned physics (do not reinvent):
  Landauer 1961     : erasing distinguishable states costs dS >= k_B ln(N_states).
  Obata 1971        : orbit of round S^3 = SO(4,1)/SO(4), a 4-dim NON-COMPACT family
                      of conformally-ISOMETRIC metrics (all equal invariant measure).
  Deser-Schwimmer   : anomaly action is topological/Weyl^2-vanishing on the
                      conformally-flat sphere => CONSTANT along the orbit.
  Zurek laundering  : S_rad = (4/3) S_BH  (repo convention), net +1/3 S_BH generated.

Consciousness/measurement is motivation ONLY and appears in NO equation below.
All entropies in nats (k_B = 1). <60 s, stdlib only.
"""
import math

# ---------------------------------------------------------------------------
# 0. Flash entropy budget  (Zurek laundering of the survivor black hole)
# ---------------------------------------------------------------------------
M_sun    = 1.989e30          # kg
m_P_kg   = 2.176e-8          # Planck mass (kg)
M_surv   = 1e11 * M_sun      # last supermassive survivor ~ 1e11 Msun

S_BH   = 4.0 * math.pi * (M_surv / m_P_kg)**2   # Bekenstein-Hawking (nats)
S_rad  = (4.0/3.0) * S_BH                         # flash radiation entropy
dS_gen = (1.0/3.0) * S_BH                         # net entropy GENERATED by evap

print("="*70)
print("FLASH BUDGET (Zurek laundering, repo convention)")
print("="*70)
print(f"  survivor mass          M      = 1e11 Msun")
print(f"  S_BH  = 4 pi (M/m_P)^2        = {S_BH:.3e} nats   (~1e{math.log10(S_BH):.1f})")
print(f"  S_rad = (4/3) S_BH            = {S_rad:.3e} nats")
print(f"  dS_gen = (1/3) S_BH  (net)    = {dS_gen:.3e} nats")

# ---------------------------------------------------------------------------
# 1. Landauer erasure cost of collapsing the Obata orbit to one member.
#
# The orbit is a 4-parameter non-compact family (1 dilation + 3 special-conformal
# directions of SO(4,1)/SO(4)). To ERASE it down to a single chosen member we must
# distinguish the members first. Number of distinguishable members:
#     N ~ (parameter range / resolution)^(d),  d = dim(orbit) = 4.
# Cost:  dS_erase = k_B ln N = d * ln(range/res).
#
# We take an ABSURDLY conservative (large) count: dilation modulus spanning the
# whole post-Planck expansion range, resolved to the Planck scale.
# ---------------------------------------------------------------------------
d_orbit = 4                       # dim SO(4,1)/SO(4)
# dilation parameter s = ln(a): from Planck era to now, ln(a_now/a_P) ~ ln(1e60) ~ 138
# special-conformal params: take a comparably huge dimensionless range, ~1e30, Planck-resolved
range_dilation = math.log(1e60)   # ~138  (e-folds of scale, generous)
N_dilation     = math.exp(range_dilation)          # = 1e60 distinguishable scales
# treat all 4 directions with a Planck-fine resolution over a range of 1e30 each:
N_percoord = 1e30
N_members  = N_percoord**d_orbit                    # = 1e120 members (wildly generous)
dS_erase   = math.log(N_members)                    # nats

print("\n" + "="*70)
print("LANDAUER ERASURE COST OF THE ORBIT COLLAPSE (deliberately over-counted)")
print("="*70)
print(f"  orbit dimension d              = {d_orbit}  (SO(4,1)/SO(4))")
print(f"  distinguishable members N      = (1e30)^4 = {N_members:.0e}  (Planck-fine, huge range)")
print(f"  dS_erase = ln N                = {dS_erase:.1f} nats")
print(f"  (even at N=1e120 members this is only ~{dS_erase:.0f} nats)")

# ---------------------------------------------------------------------------
# 2. Affordability:  dS_erase  vs  flash budget S_rad
# ---------------------------------------------------------------------------
ratio = dS_erase / S_rad
print("\n" + "="*70)
print("AFFORDABILITY  (erasure cost / flash budget)")
print("="*70)
print(f"  dS_erase / S_rad = {ratio:.3e}")
print(f"  orders of magnitude spare      = {math.log10(S_rad) - math.log10(dS_erase):.0f}")
print(f"  => the flash pays the erasure cost with ~{math.log10(S_rad/dS_erase):.0f} orders to spare.")
print(f"     AFFORDABLE: yes, overwhelmingly (dS_erase << dS_gen << S_rad).")

# ---------------------------------------------------------------------------
# 3. Is there a MINIMUM-cost member?  Per-member erasure cost across the orbit.
#
# If we KEEP member i and ERASE the rest, the cost is the Gibbs/Shannon entropy
# of the prior distribution p over members that we collapse:
#     dS_erase(i) = H(p) = -sum_j p_j ln p_j     (independent of i for erasure),
# and any i-DEPENDENCE of a min-cost RULE can only come from a NON-UNIFORM prior
# p_j, i.e. from a functional F(member_j) with p_j ~ exp(-beta F_j).
#
# Case A (anomaly / conformally-invariant F): F_j = const on the orbit
#        (Deser-Schwimmer: Weyl^2=0, Euler=topological). => p uniform => flat cost,
#        argmin degenerate  => NO selection, only a cost.
# Case B (injected symmetry-BREAKING coupling, e.g. off-sphere Weyl^2 ~ shear^2):
#        F_j non-constant => a unique argmin appears -- but it is supplied by the
#        COUPLING, not by Landauer.  Demonstrates: selection needs extra physics.
# ---------------------------------------------------------------------------
n = 2001
members = [(-2.0 + 4.0*k/(n-1)) for k in range(n)]   # orbit coordinate s in [-2,2]

def gibbs_erase_cost(F, beta=1.0):
    w = [math.exp(-beta*Fi) for Fi in F]
    Z = sum(w); p = [wi/Z for wi in w]
    H = -sum(pi*math.log(pi) for pi in p if pi > 0.0)
    return H, p

# Case A: conformally invariant functional (anomaly on the round sphere)
F_A = [0.0 for _ in members]                          # constant along orbit
H_A, p_A = gibbs_erase_cost(F_A)
imin_A = min(range(n), key=lambda k: F_A[k])
spread_A = max(F_A) - min(F_A)

# Case B: injected symmetry-breaking (off-sphere Weyl^2 ~ shear^2 ~ s^2), coeff kappa
kappa = 3.0
F_B = [kappa*(s*s) for s in members]                  # penalizes departure from s=0
H_B, p_B = gibbs_erase_cost(F_B)
imin_B = min(range(n), key=lambda k: F_B[k])
spread_B = max(F_B) - min(F_B)

print("\n" + "="*70)
print("MINIMUM-COST MEMBER?  (per-member cost across the orbit)")
print("="*70)
print("  Case A -- anomaly / conformally-INVARIANT functional (round S^3):")
print(f"     F spread along orbit        = {spread_A:.3e}   (flat)")
print(f"     erasure/Gibbs entropy H(p)  = {H_A:.3f} nats  (= ln {n}, uniform)")
print(f"     argmin member               = DEGENERATE (all {n} members tie)")
print(f"     => NO minimum-cost member. Landauer gives a COST, not a selector.")
print()
print("  Case B -- INJECTED symmetry-breaking coupling (off-sphere Weyl^2 ~ s^2):")
print(f"     F spread along orbit        = {spread_B:.3e}   (NOT flat)")
print(f"     erasure/Gibbs entropy H(p)  = {H_B:.3f} nats  (< ln {n} = {math.log(n):.3f})")
print(f"     argmin member               = s = {members[imin_B]:+.4f}  (unique)")
print(f"     => a selection appears, but it is supplied by the COUPLING kappa,")
print(f"        NOT by Landauer.  Set kappa=0 -> back to Case A (degenerate).")

# ---------------------------------------------------------------------------
# 4. Verdict
# ---------------------------------------------------------------------------
print("\n" + "="*70)
print("VERDICT")
print("="*70)
print("  (1) Erasure cost of the orbit collapse ~ few hundred nats at most;")
print(f"      flash budget S_rad ~ 1e{math.log10(S_rad):.0f} nats. Cost is AFFORDABLE by ~{math.log10(S_rad/dS_erase):.0f} orders.")
print("  (2) By conformal invariance every orbit member has EQUAL erasure cost")
print("      (equal invariant measure; anomaly F=const). No minimum-cost member.")
print("  (3) A unique argmin appears ONLY if a symmetry-BREAKING functional is")
print("      injected -- then selection comes from that coupling, not Landauer.")
print("  => Landauer supplies a CONSISTENT COST + irreversibility (needs the flash")
print("     as external reservoir), but it is NOT a selector. It does not fix phi_2.")
