#!/usr/bin/env python3
"""
CLOSURE ATTEMPT B -- entropy-production / MEPP selection for the LMU wiring joint.

Question tested: does requiring MAXIMAL entropy production across the flash
UNIQUELY select the plateau-inflation branch (over the erebon mass-term branch),
and/or fix Omega's Cauchy data (phi_1, phi_2)?

We build TWO entropy-production functionals with LMU's own numbers and compare.
Skeptical stance: MEPP has no accepted derivation (Martyushev-Seleznev 2006;
Dewar's MaxEnt attempt judged incomplete; Lineweaver: MEPP fails for cosmological
IC = no fixed boundary conditions). So a numerical winner is a RANKING, and we
explicitly test whether it is also a SELECTION (unique, bounded, fixes phi_1).

All k_B = 1 (entropy in nats/particle-equivalents). Natural units GeV where useful.
No external deps beyond math.
"""
import math

# ---------------------------------------------------------------------------
# Physical constants (SI + natural units)
# ---------------------------------------------------------------------------
G_SI     = 6.674e-11          # m^3 kg^-1 s^-2
hbar_SI  = 1.055e-34          # J s
c_SI     = 2.998e8            # m/s
kB_SI    = 1.381e-23          # J/K
m_P_kg   = 2.176e-8           # Planck mass (kg)
M_sun    = 1.989e30           # kg
M_P_GeV  = 1.221e19           # Planck mass (GeV), reduced would be 2.4e18
GeV_in_K = 1.160e13           # 1 GeV -> K
GeV_in_invm = 5.068e15        # 1 GeV -> 1/m  (hbar c = 0.1973 GeV*fm)

# ---------------------------------------------------------------------------
# LMU / repo figures
# ---------------------------------------------------------------------------
T_reh_GeV   = 1e15            # reheating temperature (LMU figure ~10^15 GeV)
g_star      = 106.75          # relativistic dof at reheating (SM)
M_survivor  = 1e11 * M_sun    # last surviving supermassive BH mass (~10^11 Msun)
m_erebon_GeV= M_P_GeV         # Penrose erebon: ~Planck mass, cold (dust, w=0)

# ---------------------------------------------------------------------------
# (0) Survivor black-hole entropy  S_BH = 4 pi (M/m_P)^2   [k_B units]
#     and Zurek laundering  S_rad = (4/3) S_BH  (net +1/3 S_BH generated)
# ---------------------------------------------------------------------------
S_BH   = 4.0 * math.pi * (M_survivor / m_P_kg)**2
S_rad_zurek = (4.0/3.0) * S_BH
dS_zurek    = (1.0/3.0) * S_BH      # net entropy GENERATED by evaporation

# ---------------------------------------------------------------------------
# BRANCH A -- plateau inflation -> reheating.
# Functional: the flash kicks omega onto the alpha=1 plateau; it inflates,
# then reheats a horizon patch to T_reh, thermalizing vacuum energy into a
# relativistic bath. Entropy-production functional = radiation entropy created.
#
#   entropy density  s = (2 pi^2/45) g_* T^3          (natural units, GeV^3)
#   energy density   rho = (pi^2/30) g_* T^4
#   Hubble at reheat H^2 = rho / (3 Mpl_red^2)  ~  rho/(3 (M_P/sqrt(8pi))^2)
#   horizon volume   V_H = (4 pi/3) H^-3
#   S_A(horizon)     = s * V_H
# We also give the comoving/observable-universe number (adiabatically conserved
# after reheating) ~ today's radiation entropy for cross-check.
# ---------------------------------------------------------------------------
def branch_A_horizon_entropy(T_GeV, g=g_star):
    Mpl_red_GeV = M_P_GeV / math.sqrt(8.0*math.pi)      # reduced Planck mass
    s_dens_GeV3  = (2.0*math.pi**2/45.0) * g * T_GeV**3   # GeV^3
    rho_GeV4     = (math.pi**2/30.0) * g * T_GeV**4       # GeV^4
    H_GeV        = math.sqrt(rho_GeV4 / (3.0*Mpl_red_GeV**2))
    # convert to inverse metres then metres
    H_invm       = H_GeV * GeV_in_invm
    V_H_m3       = (4.0*math.pi/3.0) * H_invm**(-3)
    # entropy density in 1/m^3:  s(GeV^3) * (GeV_in_invm)^3
    s_dens_invm3 = s_dens_GeV3 * GeV_in_invm**3
    S_horizon    = s_dens_invm3 * V_H_m3
    return S_horizon, H_GeV

S_A_horizon, H_reh = branch_A_horizon_entropy(T_reh_GeV)

# Comoving observable-universe radiation entropy (standard result, cross-check):
# today ~ 1.5e88 (CMB) + neutrinos -> ~2.9e88 ; often quoted ~1e88-1e90.
S_A_comoving_obs = 2.9e88

# ---------------------------------------------------------------------------
# BRANCH B -- erebon mass term (Penrose dark matter).
# omega becomes a Planck-mass massive scalar (cold, w=0). NO reheating bath:
# rest-mass gas, entropy ~ number of quanta * O(1), no thermalization.
# For the SAME energy budget E that branch A thermalizes at T_reh, compare:
#   radiation: N_rad ~ E / T_reh   quanta  -> S ~ N_rad   (S ~ E/T, k_B=1)
#   erebons:   N_ereb ~ E / m_ereb quanta  -> S ~ N_ereb  (cold dust, ~1 nat each)
# So per unit energy, S_A/S_B ~ m_ereb / T_reh.
# ---------------------------------------------------------------------------
ratio_per_energy = m_erebon_GeV / T_reh_GeV     # entropy advantage of A over B
# Scale branch A horizon entropy down by that ratio to get the erebon-branch
# entropy for the SAME horizon energy budget:
S_B_horizon = S_A_horizon / ratio_per_energy

# ---------------------------------------------------------------------------
# (2) MONOTONICITY / SELECTION test.
# entropy production of branch A grows with reheating volume ~ e^{3 N_efold}
# (more e-folds -> more reheated comoving volume -> more entropy). Show that
# "maximize S" is UNBOUNDED in N: it does NOT pick a finite plateau amplitude.
# ---------------------------------------------------------------------------
def S_A_vs_efolds(N):
    # comoving entropy after reheating scales with the volume inflated then
    # reheated; take S ~ S0 * exp(3*(N - N0)) with N0=60 anchor at S_A_comoving_obs
    N0 = 60.0
    return S_A_comoving_obs * math.exp(3.0*(N - N0))

efold_scan = [(N, S_A_vs_efolds(N)) for N in (60, 65, 70, 80, 100)]

# ---------------------------------------------------------------------------
# REPORT
# ---------------------------------------------------------------------------
def sci(x):
    return f"{x:.2e}"

print("="*72)
print("CLOSURE ATTEMPT B -- entropy-production / MEPP branch selection")
print("="*72)
print()
print("[0] Survivor black hole + Zurek laundering (flash reservoir):")
print(f"    M_survivor        = 1e11 M_sun")
print(f"    S_BH = 4pi(M/m_P)^2 = {sci(S_BH)}  k_B")
print(f"    S_rad = (4/3)S_BH   = {sci(S_rad_zurek)}  k_B   (Zurek 1982)")
print(f"    net dS generated    = (1/3)S_BH = {sci(dS_zurek)}  k_B  (arrow measure)")
print()
print("[A] BRANCH A  plateau -> inflation -> reheating (T_reh=1e15 GeV, g*=106.75):")
print(f"    H_reheat            = {sci(H_reh)} GeV")
print(f"    S_A (one horizon)   = {sci(S_A_horizon)}  k_B")
print(f"    S_A (obs. universe, comoving cross-check) ~ {sci(S_A_comoving_obs)} k_B")
print()
print("[B] BRANCH B  erebon mass term (cold, m~M_P, w=0, NO reheating bath):")
print(f"    S_A/S_B per unit energy = m_ereb/T_reh = {sci(ratio_per_energy)}")
print(f"    S_B (same horizon energy) = {sci(S_B_horizon)}  k_B")
print()
print("[1] RANKING:")
print(f"    S_A / S_B          = {sci(S_A_horizon/S_B_horizon)}")
print(f"    -> plateau branch produces ~{sci(S_A_horizon/S_B_horizon)}x MORE entropy.")
print(f"    MEPP would RANK plateau > erebon. Unambiguous ranking.")
print()
print("[2] SELECTION test -- is the max BOUNDED / does it fix a finite amplitude?")
print("    S_A vs e-folds N (monotone increasing, no interior maximum):")
for N, S in efold_scan:
    print(f"      N={N:3d}   S_A ~ {sci(S)}  k_B")
print("    -> 'maximize entropy production' is UNBOUNDED in N (more inflation")
print("       = more entropy, runaway toward eternal inflation). There is NO")
print("       interior extremum, so MEPP does NOT select a finite plateau")
print("       amplitude phi_1. It only breaks the A-vs-B tie by ranking.")
print()
print("[VERDICT]")
print("  * Ranks branches: YES (plateau >> erebon, ~%s x)." % sci(S_A_horizon/S_B_horizon))
print("  * Derivation of selection: NO. MEPP has no accepted derivation")
print("    (Martyushev-Seleznev 2006; Dewar incomplete). This is a POST-HOC")
print("    ranking read off after assuming the alpha-attractor potential.")
print("  * Fixes Omega Cauchy data (phi_1,phi_2): NO. S is monotone/unbounded")
print("    in N -> no interior max -> phi_1 (amplitude) stays free. phi_2 (the")
print("    delayed-rest-mass mode) is untouched entirely.")
print("  * Rigorous residue that DOES survive: the flash->plateau landing can be")
print("    framed as the FW/instanton most-probable PATH (Santolin-Esposito-")
print("    Falasco 2025 bound ln r <= -int sigma_dot), but that selects a")
print("    TRAJECTORY given the potential, not the potential/amplitude/IC.")
print("="*72)
